apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  namespace: chris
  labels:
    app: nginx1
  annotations:
    config.kubernetes.io/depends-on: /namespaces/chris/Service/chris-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx
        image: nginx2:1.14.2
        ports:
        - containerPort: 80