apiVersion: v1
kind: Namespace
metadata:
  name: a
---
apiVersion: v1
kind: Namespace
metadata:
  name: b
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: a-clone
data:
  env: prod
